services:
  - type: web
    name: flextraff-backend
    env: python
    plan: free  # Change to 'starter' or 'standard' for production
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PORT
        value: 10000
    healthCheckPath: /health